### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by quamejnr** [hacktivist123/goignore#1]
Finding it difficult to get this working locally after cloning the directory.
- `go build` leads to the error `runtime.main_main·f: function main is undeclared in the main package`
- `go run cmd/goignore/main.go` also leads to the error `package command-line-arguments is not a main package`

Also, tried getting in one of my projects and after running `go get github.com/hacktivist123/goignore`, got this error 
`go: github.com/hacktivist123/goignore@v1.0.0: parsing go.mod:
        module declares its path as: goignore
                but was required as: github.com/hacktivist123/goignore`

**Comment by hacktivist123** [comment]
Hello, please can you share what OS you’re on?

**Comment by hacktivist123** [comment]
Hello, there's a new fix, check README for an updated instruction on how to install
