### ISSUE TITLE
let goignore automatically detect the language by default

### ISSUE THREAD

**Issue by noornee** [hacktivist123/goignore#10]
hii, @hacktivist123 it would be nice if  `goignore` automatically detects the language by default instead of adding the `--language=auto` flag

it should detect  automatically just by doing

```bash
$ goignore new
```
\-
\-
great project btw ;)

**Comment by hacktivist123** [comment]
This makes sense actually, will add it to the next release. 

Thanks for the idea

**Comment by noornee** [comment]
> This makes sense actually, will add it to the next release.

yepp

> Thanks for the idea

glad i could help!
