### ISSUE TITLE
The Logic in the PersistentPreRun section is causing a bug

### ISSUE THREAD

**Issue by noornee** [hacktivist123/goignore#14]
The Logic in the PersistentPreRun [section here](https://github.com/hacktivist123/goignore/blob/fc5ea9c36d13b9bdc2b1f1cfdd2457a98f55e4ab/cmd/goignore/main.go#L138) is preventing me from getting the help for any commands

# SCREENSHOTS

**buggy-version:**

![goignore-bug-1](https://github.com/hacktivist123/goignore/assets/71889751/d1b94126-43d2-463b-9d01-fe8aaf7bb0be)

**fixed-version:**

![goignore-fix](https://github.com/hacktivist123/goignore/assets/71889751/873c8c94-35a9-4937-9720-0154181c0cee)

**Comment by hacktivist123** [comment]
This is awesome, can you confirm if the language=auto and every other command works? If so please send a PR with your fix.

**Comment by noornee** [comment]
> This is awesome, can you confirm if the language=auto and every other command works? If so please send a PR with your fix.

alrighttt
