### ISSUE TITLE
Bug: Language detection 

### ISSUE THREAD

**Issue by chuksgpfr** [hacktivist123/goignore#19]
The [PR](https://github.com/hacktivist123/goignore/pull/4) for language detection, loops through the array and replaces the latest extension with the latter.

e.g. If the last file to walk through is a .js file in a typescript codebase, the language is detected as Javascript.

@hacktivist123

**Comment by hacktivist123** [comment]
Oh yes, I haven’t created a specific file for typescript projects yet so since Typescript is mostly JavaScript. I just default to generating a JavaScript gitignore for ts files for now. 

Unless I didn’t get your issue

**Comment by chuksgpfr** [comment]
Check the PR I'll open next (I'll leave it as a draft), You can let me know if you want me to test it and you can merge it.

**Comment by chuksgpfr** [comment]
My [draft PR](https://github.com/hacktivist123/goignore/pull/20)

@hacktivist123

**Comment by hacktivist123** [comment]
Oh shit, I get it now. 

I didn’t consider this edge case, damn! Good catch. 

I’ll test it out and merge. 

Open the PR for merge

**Comment by chuksgpfr** [comment]
I will do that, I need to ignore directories that start with (.). The WalkDir traverses through .git directory  🥲

**Comment by hacktivist123** [comment]
fixed in #20
