### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by quamejnr** [hacktivist123/goignore#3]
I am unable to add it to my project. `go get -u github.com/hacktivist123/goignore/cmd/goignore` gives an error 
`module declares its path as: goignore
                but was required as: github.com/hacktivist123/goignore`

I'm using MacOS

**Comment by hacktivist123** [comment]
i see, so there's a new release. 

add @v1.0.1 and you're good to go

**Comment by quamejnr** [comment]
Still unable to use it in my project. `goignore` command is not recognized

**Comment by hacktivist123** [comment]
Interesting, let me work on a fix and get back to you. 

Thank you so much for the feedback

**Comment by hacktivist123** [comment]
fixed, thanks
