### ISSUE TITLE
Should be binary file

### ISSUE THREAD

**Issue by quamejnr** [hacktivist123/goignore#8]
Since the software should allow you to generate multiple files I wanted you to consider making it a binary file instead of a package. That way one can just download the file and generate their gitignore file on any project without having to install golang

**Comment by hacktivist123** [comment]
Saw you sent a fix for this, thanks mate. Will merge

**Comment by quamejnr** [comment]
Was hoping github actions will be created so any new push will create an executable file that can be downloaded. Not too familiar with it, saw this online, don't know if it will be helpful. Saw these examples https://github.com/wangyoucao577/go-release-action/wiki/More-Examples
They might be helpful

**Comment by hacktivist123** [comment]
Just created an action to just build the project for now. 

You're correct WTH your suggestion, I'll implement it over the weekend.
